Jeu:main.o temps.o 
	gcc main.o temps.o  -o Jeu -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -lm -g

main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g


temps.o:temps.c
	gcc -c temps.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g

