
p:main.o  deplacement.o
	gcc main.o   deplacement.o -o p -lSDL -lSDL_image -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -g
deplacement.o:deplacement.c
	gcc -c deplacement.c -lSDL -lSDL_image -g
